# Generated by Django 5.0.7 on 2024-09-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(choices=[('Train A', 'Train A'), ('Train B', 'Train B'), ('Train C', 'Train C')], default='Train A', max_length=100)),
                ('start_station', models.CharField(max_length=100)),
                ('dest_station', models.CharField(max_length=100)),
                ('pnr', models.CharField(max_length=12, unique=True)),
                ('booking_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10)),
            ],
        ),
    ]
