# Generated by Django 5.0.7 on 2024-09-22 05:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_of_journey',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
