# Generated by Django 5.0.7 on 2024-09-22 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_booking_date_of_journey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=100)),
                ('start_station', models.CharField(max_length=100)),
                ('dest_station', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='train_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.schedule'),
        ),
    ]
