# Generated by Django 5.0.7 on 2024-09-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_schedule_alter_booking_train_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
