# Generated by Django 5.0.7 on 2024-10-03 19:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_booking_pnr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('journey_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
            ],
            options={
                'db_table': 'journey',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_code', models.CharField(max_length=10)),
                ('station_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.IntegerField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'train',
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='train_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date_of_journey',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='dest_station',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_station',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pnr',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=255, verbose_name='Passenger Name')),
                ('email', models.EmailField(help_text='Enter a valid email address.', max_length=255, unique=True)),
                ('phone_number', models.CharField(help_text='Enter your phone number.', max_length=15)),
                ('age', models.IntegerField(help_text='Age must be a non-negative integer.', validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Passengers',
                'db_table': 'passenger',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.passenger'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_seats', models.IntegerField()),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.journey')),
            ],
            options={
                'db_table': 'seat',
            },
        ),
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.journey')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.passenger')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.seat')),
                ('end_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seatbooking_end_station_set', to='registration.station')),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.station')),
            ],
            options={
                'db_table': 'seat_booking',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='booking',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.seatbooking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journey',
            name='dest_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_dest_station_set', to='registration.station'),
        ),
        migrations.AddField(
            model_name='journey',
            name='src_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.station'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('stop_order', models.IntegerField()),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.station')),
                ('train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.train')),
            ],
            options={
                'db_table': 'route',
            },
        ),
        migrations.AddField(
            model_name='journey',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.train'),
        ),
        migrations.CreateModel(
            name='TrainCarriage',
            fields=[
                ('carriage_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=10)),
                ('seating_capacity', models.IntegerField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.train')),
            ],
            options={
                'db_table': 'train_carriage',
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='carriage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.traincarriage'),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
