# Generated by Django 5.0.7 on 2024-10-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_booking_date_of_journey_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_of_journey',
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('journey', 'carriage')},
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='journey_date',
            field=models.DateField(null=True),
        ),
        migrations.RemoveField(
            model_name='seat',
            name='available_seats',
        ),
    ]
