# Generated by Django 5.0.7 on 2024-11-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_remove_booking_date_of_journey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traincarriage',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
