# Generated by Django 5.0.7 on 2024-11-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_seat_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(help_text='Enter a valid email address.', max_length=255),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passenger_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Passenger Name'),
        ),
    ]
