# Generated by Django 5.0.7 on 2024-11-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_alter_passenger_email_alter_passenger_passenger_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(help_text='Enter a valid email address.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passenger_name',
            field=models.CharField(max_length=255, verbose_name='Passenger Name'),
        ),
    ]
