# Generated by Django 5.0.7 on 2024-11-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_alter_passenger_email_alter_passenger_passenger_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatbooking',
            name='journey_date',
            field=models.DateField(),
        ),
    ]
